A = ("An","Binh","Long","Ngoc","Tu")
B = ("Binh","Linh","Nam","Hai","Long")
A = set(A)
A.remove('Tu')
print(A)
A.add('Cuong')
print(A)
print(A|set(B))
D=tuple(A)+tuple(B)
print(D)
E=(A-set(B))
print(E)
F=(A^set(B))
print(F)